name: utils
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^5.0.1
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
